### ISSUE TITLE
Add option to only enable hover content on :hoverref: and :glossary:

### ISSUE THREAD

**Issue by Daltz333** [readthedocs/sphinx-hoverxref#74] opened 2020-05-16 00:26 UTC
Similar to ``hoverxref_auto_ref`` but with ``hoverxref_auto_glossary``

**Comment by humitos** [comment] 2020-05-17 13:23
I think you can achieve this by using `hoverxref_roles = ['term']`, right? If so, I don't think we should add another specific config just for `term`. Please let me know.

**Comment by Daltz333** [comment] 2020-05-17 14:32
That's correct.

**Comment by humitos** [comment] 2020-05-18 11:20
Thanks! I don't think we need to add another config for this. In fact, I'd say that we should go the other way arround and remove `auto_ref` at some point.

Originally, `hoverxref_roles` didn't exist. `hoverxref_auto_ref` could be replaced just by adding `ref` into `hoverxref_roles`.

I'm closing this issue because it's not a bug and I don't think we will add a new config for this. Besides, there is a way to make it work.

**Closed by humitos** 2020-05-18 11:20 UTC
Labels: Needed: more information
