### ISSUE TITLE
Intersphinx integration

### ISSUE THREAD

**Issue by rayzchen** [readthedocs/sphinx-hoverxref#181] opened 2022-05-16 16:01 UTC
Links to Python types (like [str](https://docs.python.org/3/library/stdtypes.html#str)) don't generate tooltips

**Comment by humitos** [comment] 2022-05-30 11:09
@rayzchen is this issue a duplicate of https://github.com/readthedocs/sphinx-hoverxref/issues/177 ?

**Comment by rayzchen** [comment] 2022-05-30 11:11
Possibly? I haven't had enough time to experiment and find which option fixes it.

**Comment by humitos** [comment] 2022-05-30 12:57
What's the rst syntax that you are using to add these intersphinx links?

**Comment by humitos** [comment] 2022-05-30 13:02
I just tested this and using 
```
:py:class:`str`
```

I was able to make it work and link to https://docs.python.org/3/library/stdtypes.html#str and show a tooltip.

![Screenshot_2022-05-30_15-02-01](https://user-images.githubusercontent.com/244656/170997977-535f5100-eade-47ad-86a1-df8622ba9c38.png)

Feel free to re-open if you consider. Thanks!

**Closed by humitos** 2022-05-30 13:02 UTC
Labels: Needed: more information
